version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: bus_tracking_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bus_tracking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bus_tracking_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: bus_tracking_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bus_tracking_network

  # Node.js API Application
  api:
    build: .
    container_name: bus_tracking_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=bus_tracking
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_key_here_change_in_production
    depends_on:
      - postgres
      - redis
    networks:
      - bus_tracking_network

volumes:
  postgres_data:
  redis_data:

networks:
  bus_tracking_network:
    driver: bridge